DELETE FROM [semanticinsight].[process]
DELETE FROM [semanticinsight].[data_type] 
DELETE FROM [semanticinsight].[load_pattern_attribute]						 
DELETE FROM [semanticinsight].[system_framework_attribute]
DELETE FROM [semanticinsight].[load_pattern]
DELETE FROM [semanticinsight].[system_framework]
DELETE FROM [semanticinsight].[data_object_type]